# Generated by Django 4.2.29 on 2026-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_backfill_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Напр.: 38,39,40,41 або S,M,L', max_length=220, verbose_name='Доступні розміри'),
        ),
    ]
