# Generated by Django 4.2.29 on 2026-04-22 20:13

from django.db import migrations


def forwards(apps, schema_editor):
    Product = apps.get_model('bikes', 'Product')
    Review = apps.get_model('bikes', 'Review')

    # Seed sizes for common gear types if missing
    shoes_qs = Product.objects.filter(category__gear_type='shoes')
    for p in shoes_qs:
        if not (p.available_sizes or '').strip():
            p.available_sizes = '38,39,40,41,42,43,44,45'
            p.save(update_fields=['available_sizes'])

    helmets_qs = Product.objects.filter(category__gear_type='helmet')
    for p in helmets_qs:
        if not (p.available_sizes or '').strip():
            p.available_sizes = 'S,M,L'
            p.save(update_fields=['available_sizes'])

    gloves_qs = Product.objects.filter(category__gear_type='gloves')
    for p in gloves_qs:
        if not (p.available_sizes or '').strip():
            p.available_sizes = 'S,M,L,XL'
            p.save(update_fields=['available_sizes'])

    clothing_qs = Product.objects.filter(category__gear_type='clothing')
    for p in clothing_qs:
        if not (p.available_sizes or '').strip():
            p.available_sizes = 'XS,S,M,L,XL'
            p.save(update_fields=['available_sizes'])

    # Seed demo reviews for products with no reviews (diploma-ready)
    demo = [
        ('Оля', 5, 'Дуже зручно, розмір підійшов. Якість топ.'),
        ('Андрій', 4, 'Все ок, але хотілось би більше кольорів.'),
        ('Марія', 5, 'Легко, комфортно, рекомендую для початківців.'),
    ]

    products = Product.objects.all()[:40]
    for p in products:
        if Review.objects.filter(product_id=p.id).exists():
            continue
        # Add 1–2 reviews depending on category
        rows = demo[:2] if p.category.category_type == 'bike' else demo
        for author, rating, text in rows[:2]:
            Review.objects.create(product_id=p.id, author=author, rating=rating, text=text)

        # Recompute rating fields on Product (simple average)
        qs = Review.objects.filter(product_id=p.id)
        cnt = qs.count()
        if cnt:
            total = 0
            for r in qs:
                total += int(r.rating)
            p.rating = round(total / cnt, 2)
            p.reviews_count = cnt
            p.save(update_fields=['rating', 'reviews_count'])


def backwards(apps, schema_editor):
    # Keep user-generated content; do not delete reviews on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_product_available_sizes'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
