# Generated by GPT-5.2 on 2026-04-22

from django.db import migrations


def backfill_product_images(apps, schema_editor):
    Product = apps.get_model('bikes', 'Product')
    ProductImage = apps.get_model('bikes', 'ProductImage')

    qs = Product.objects.all().only('id', 'image', 'image_url', 'name')
    to_create = []
    for p in qs.iterator():
        has_gallery = ProductImage.objects.filter(product_id=p.id).exists()
        if has_gallery:
            continue
        # Use existing "main" image as the first gallery image
        if getattr(p, 'image', None):
            to_create.append(
                ProductImage(
                    product_id=p.id,
                    image=p.image,
                    image_url='',
                    alt=p.name or '',
                    sort_order=0,
                )
            )
        elif getattr(p, 'image_url', ''):
            to_create.append(
                ProductImage(
                    product_id=p.id,
                    image=None,
                    image_url=p.image_url,
                    alt=p.name or '',
                    sort_order=0,
                )
            )

    if to_create:
        ProductImage.objects.bulk_create(to_create, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    # Data migration is intentionally not reversed.
    return


class Migration(migrations.Migration):
    dependencies = [
        ('bikes', '0009_productimage'),
    ]

    operations = [
        migrations.RunPython(backfill_product_images, noop_reverse),
    ]

