# Generated by Django 5.2.13 on 2026-04-29 19:23

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0019_ride_posts_and_subscriptions'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
