# Generated by Django 5.2.13 on 2026-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0020_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Жіноча'), ('male', 'Чоловіча'), ('other', 'Інше'), ('na', 'Не вказувати')], default='na', max_length=10, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ріст (см)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вага (кг)'),
        ),
    ]
